spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    test:
      url: jdbc:mysql://1.15.69.146:33306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    test2:
      url: jdbc:mysql://1.15.69.146:33306/test2?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver




